/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'driverId' : bigint,
  'endDate' : bigint,
  'customerPhone' : string,
  'customerPrincipal' : Principal,
  'feedbackMessage' : [] | [string],
  'sosFlag' : boolean,
  'pickupAddress' : string,
  'daysCount' : bigint,
  'insuranceOpted' : boolean,
  'createdTimestamp' : bigint,
  'totalPrice' : bigint,
  'customerEmail' : string,
  'dropAddress' : string,
  'startDate' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface DriverProfile {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'languages' : Array<string>,
  'isAvailable' : boolean,
  'photoUrl' : string,
  'trustBadges' : Array<string>,
  'pricePerDay' : bigint,
  'state' : string,
  'experienceYears' : bigint,
  'isVerified' : boolean,
  'rating' : bigint,
  'phone' : string,
}
export interface DriverRegistrationRequest {
  'id' : bigint,
  'paymentStatus' : boolean,
  'submissionTimestamp' : bigint,
  'city' : string,
  'name' : string,
  'selfieDoc' : ExternalBlob,
  'email' : string,
  'state' : string,
  'aadharDoc' : ExternalBlob,
  'licenseDoc' : ExternalBlob,
  'phone' : string,
  'panDoc' : ExternalBlob,
  'verificationStatus' : RegistrationStatus,
  'requesterPrincipal' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface OtpLoginRecord {
  'name' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SavedAddress {
  'addressLabel' : string,
  'address' : string,
  'customerId' : Principal,
}
export interface SubscriptionEnquiry {
  'id' : bigint,
  'familyMembersCount' : bigint,
  'city' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'planType' : string,
  'requesterPrincipal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDriverRegistration' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'confirmBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      boolean,
    ],
    bigint
  >,
  'filterDriversByCity' : ActorMethod<[string], Array<DriverProfile>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllDrivers' : ActorMethod<[], Array<DriverProfile>>,
  'getAllEnquiries' : ActorMethod<[], Array<SubscriptionEnquiry>>,
  'getAllRegistrations' : ActorMethod<[], Array<DriverRegistrationRequest>>,
  'getBookingsByCustomer' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriverById' : ActorMethod<[bigint], [] | [DriverProfile]>,
  'getOtpLoginRecords' : ActorMethod<[], Array<OtpLoginRecord>>,
  'getSavedAddresses' : ActorMethod<[], Array<SavedAddress>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeApp' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAvailableDrivers' : ActorMethod<[], Array<DriverProfile>>,
  'markSosForBooking' : ActorMethod<[bigint], undefined>,
  'recordOtpLogin' : ActorMethod<[string, string], undefined>,
  'registerDriver' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
    ],
    bigint
  >,
  'removeDriver' : ActorMethod<[bigint], undefined>,
  'saveAddress' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFeedbackMessage' : ActorMethod<[bigint, string], undefined>,
  'submitSubscriptionEnquiry' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    bigint
  >,
  'updateDriverRate' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];