/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DriverProfile = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'isAvailable' : IDL.Bool,
  'photoUrl' : IDL.Text,
  'trustBadges' : IDL.Vec(IDL.Text),
  'pricePerDay' : IDL.Nat,
  'state' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'driverId' : IDL.Nat,
  'endDate' : IDL.Int,
  'customerPhone' : IDL.Text,
  'customerPrincipal' : IDL.Principal,
  'feedbackMessage' : IDL.Opt(IDL.Text),
  'sosFlag' : IDL.Bool,
  'pickupAddress' : IDL.Text,
  'daysCount' : IDL.Nat,
  'insuranceOpted' : IDL.Bool,
  'createdTimestamp' : IDL.Int,
  'totalPrice' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'dropAddress' : IDL.Text,
  'startDate' : IDL.Int,
});
export const SubscriptionEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'familyMembersCount' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'planType' : IDL.Text,
  'requesterPrincipal' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DriverRegistrationRequest = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Bool,
  'submissionTimestamp' : IDL.Int,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'selfieDoc' : ExternalBlob,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'aadharDoc' : ExternalBlob,
  'licenseDoc' : ExternalBlob,
  'phone' : IDL.Text,
  'panDoc' : ExternalBlob,
  'verificationStatus' : RegistrationStatus,
  'requesterPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const OtpLoginRecord = IDL.Record({
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const SavedAddress = IDL.Record({
  'addressLabel' : IDL.Text,
  'address' : IDL.Text,
  'customerId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDriverRegistration' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'filterDriversByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DriverProfile)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(SubscriptionEnquiry)], ['query']),
  'getAllRegistrations' : IDL.Func(
      [],
      [IDL.Vec(DriverRegistrationRequest)],
      ['query'],
    ),
  'getBookingsByCustomer' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverById' : IDL.Func([IDL.Nat], [IDL.Opt(DriverProfile)], ['query']),
  'getOtpLoginRecords' : IDL.Func([], [IDL.Vec(OtpLoginRecord)], ['query']),
  'getSavedAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeApp' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAvailableDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
  'markSosForBooking' : IDL.Func([IDL.Nat], [], []),
  'recordOtpLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerDriver' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
      ],
      [IDL.Nat],
      [],
    ),
  'removeDriver' : IDL.Func([IDL.Nat], [], []),
  'saveAddress' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFeedbackMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitSubscriptionEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateDriverRate' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DriverProfile = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'isAvailable' : IDL.Bool,
    'photoUrl' : IDL.Text,
    'trustBadges' : IDL.Vec(IDL.Text),
    'pricePerDay' : IDL.Nat,
    'state' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'driverId' : IDL.Nat,
    'endDate' : IDL.Int,
    'customerPhone' : IDL.Text,
    'customerPrincipal' : IDL.Principal,
    'feedbackMessage' : IDL.Opt(IDL.Text),
    'sosFlag' : IDL.Bool,
    'pickupAddress' : IDL.Text,
    'daysCount' : IDL.Nat,
    'insuranceOpted' : IDL.Bool,
    'createdTimestamp' : IDL.Int,
    'totalPrice' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'dropAddress' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const SubscriptionEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'familyMembersCount' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'planType' : IDL.Text,
    'requesterPrincipal' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DriverRegistrationRequest = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Bool,
    'submissionTimestamp' : IDL.Int,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'selfieDoc' : ExternalBlob,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'aadharDoc' : ExternalBlob,
    'licenseDoc' : ExternalBlob,
    'phone' : IDL.Text,
    'panDoc' : ExternalBlob,
    'verificationStatus' : RegistrationStatus,
    'requesterPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OtpLoginRecord = IDL.Record({
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const SavedAddress = IDL.Record({
    'addressLabel' : IDL.Text,
    'address' : IDL.Text,
    'customerId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDriverRegistration' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'filterDriversByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DriverProfile)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(SubscriptionEnquiry)], ['query']),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(DriverRegistrationRequest)],
        ['query'],
      ),
    'getBookingsByCustomer' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverById' : IDL.Func([IDL.Nat], [IDL.Opt(DriverProfile)], ['query']),
    'getOtpLoginRecords' : IDL.Func([], [IDL.Vec(OtpLoginRecord)], ['query']),
    'getSavedAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeApp' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAvailableDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
    'markSosForBooking' : IDL.Func([IDL.Nat], [], []),
    'recordOtpLogin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerDriver' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
        ],
        [IDL.Nat],
        [],
      ),
    'removeDriver' : IDL.Func([IDL.Nat], [], []),
    'saveAddress' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFeedbackMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitSubscriptionEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateDriverRate' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };